trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - '*'

resources:
  containers:
    - container: wtmp-mssql-docker-db
      image: mcr.microsoft.com/mssql/server:2019-latest
      options: '--name wtmp-mssql-docker-db'
      env:
        SA_PASSWORD: x2yiJt!Fs
        ACCEPT_EULA: y
      ports:
        - 1444:1433

    - container: azurite
      image: mcr.microsoft.com/azure-storage/azurite
      ports:
        - 10000:10000
        - 10001:10001

stages:
  - stage: 'Test_container'
    displayName: 'Test_container'
    jobs:
      - job: 'Test_container'
        displayName: 'Test_container'
        pool:
          vmImage: 'ubuntu-latest'
        services:
          wtmp-mssql-docker-db: wtmp-mssql-docker-db
          azurite: azurite
        
        steps:
          - task: PowerShell@2
            displayName: 'Wait for container'
            timeoutInMinutes: 5
            inputs:
              targetType: 'inline'
              script: ./wait_database.ps1